# Generated by Django 3.1.5 on 2021-01-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_string', models.TextField()),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
